### PR TITLE
update log2, log10

### PR DESCRIPTION
**Pull request by Yaffle**

### CODE REVIEW

**Comment by rtoy** [comment]
Sorry, I don't understand the point of this pull request.

It looks like you've basically made the log functions depend on the existing log functions defined by Javascript.  That basically defeats the purpose of these routines which was to provide an implementation of the log functions of Javascript, especially if your implementation of Javascript has inaccurate versions.

Can you explain what you're trying to do here?

**Comment by Yaffle** [comment]
@rtoy, but you are using native `Math.log` too.

`ilogb` is exact, `scalbn` is exact too
Those functions mimic function with same name in "c++ library":
http://www.cplusplus.com/reference/cmath/ilogb/
http://www.cplusplus.com/reference/cmath/scalbn/

**Comment by rtoy** [comment]
Thanks for the explanation.  Yeah, log10 does call Math.log.  That should probably call fdlibm's log function instead.

While ilogb is exact, I'm not sure your implementation is.  You have 3 rounding operations, and there's no guarantee that Math.log is even correct. Calling Math.log twice (once in ilobg, once for the final result) to compute log10 isn't really great for speed  either.  These routines are intended to be reasonably fast assuming the compiler does a good job with _ConstructDouble/_DoubleHi/_DoubleLo.

LIkewise for scalbn, you're expecting Math.pow() to be exact.  No guarantee on that either.

But I do see that log10 should replace Math.pow(2,54) with the actual constant in case the compiler isn't smart enough to constant fold that. 

log2 was carefully computed in two parts for accuracy.  You have just just Math.LOG2E \* Math.log(scalbn(x, -e)) + e which has 2 rounding operations and a dependency on Math.log returning accurate values.

And it's not clear to me that your replacements return as accurate values as before. Did you run the test suite with your changes?  (The test suite isn't great for testing accuracy, but it does do some basic tests on accuracy for various values.)

What is your actual goal for this change?  Just to simplify the code?

**Comment by Yaffle** [comment]
@rtoy ,
`Math.log` should have an absolute error >= 0.5 to make my `ilogb` incorrect.
yes, the goal was to simplify the code. And I never met a web browser with inexact `Math.pow(2, n)`.

You can always implement `ilogb` and `scalbn` using typed arrays if you like:

```
// incorrect for subnormals
var ilogb = function (x) {
    return (_DoubleHi(x) >> 20) - 1023;
};
// n should be between -1023 and 1022
var scalbn = function (x, n) {
    return x / _ConstructDouble((1023 - n) << 20, 0);
};
```

Probably, your `log2` is a little more exact so.
But my should be monotonic and have exact results for exact powers of 2 in case `Math.log` is not too inexact.
Of course I ran your tests.

**Comment by Yaffle** [comment]
ok, if you have `log2` with 0.5 ulp precision... I am closing my pull request

**Comment by rtoy** [comment]
Actually, no, I don't think log2 is accurate to 0.5 ulp. I don't think any part of fdlibm is that accurate.  At best < 1 ulp, but some parts are worse.

**Pull request closed without merging**
